[tool.poetry]
name = "marvel-bot"
version = "0.4.0"
description = "Simple bot that fetch data from Marvel API and tweet every X amount of time information of a random character."
authors = ["Ariel Parra <darkaico@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
tweepy = "^3.8.0"
python-dotenv = "^0.13.0"
dacite = "^1.5.0"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
pytest-mock = "^3.1.1"
faker = "^4.1.1"
schedule = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
