[tool.poetry]
name = "marvel-bot"
version = "0.5.0"
description = "Simple bot that fetch data from Marvel API and tweet every X amount of time information of a random character."
authors = ["Ariel Parra <darkaico@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.0"
tweepy = "^3.8.0"
python-dotenv = "^0.13.0"
dacite = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-mock = "^3.1.1"
faker = "^4.1.1"
pytest-cov = "^2.10.1"
black = {version = "^20.8b1", allow-prereleases = true}
ipdb = "^0.13.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
