[tool.poetry]
name = "marvel-bot"
version = "0.7.0"
description = "Simple bot that fetch data from Marvel API and tweet every X amount of time information of a random character."
authors = ["Ariel Parra <darkaico@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
tweepy = "^3.8.0"
python-dotenv = "^0.13.0"
dacite = "^1.5.0"
schedule = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-mock = "^3.6.1"
faker = "^4.18.0"
pytest-cov = "^2.12.1"
ipdb = "^0.13.9"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
